package com.example.wellnessapp.ui.ai

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.recyclerview.widget.RecyclerView
import com.example.wellnessapp.R
import com.example.wellnessapp.data.model.AiAdviceResponse

class AiAdviceHistoryAdapter(
    private val onItemClick: (AiAdviceResponse) -> Unit
) : RecyclerView.Adapter<AiAdviceHistoryAdapter.AdviceHistoryViewHolder>() {

    private val items =
        mutableListOf<AiAdviceResponse>()

    fun submitItems(newItems: List<AiAdviceResponse>) {
        items.clear()
        items.addAll(newItems)
        notifyDataSetChanged()
    }

    override fun onCreateViewHolder(
        parent: ViewGroup,
        viewType: Int
    ): AdviceHistoryViewHolder {
        val view =
            LayoutInflater.from(parent.context)
                .inflate(
                    R.layout.item_ai_advice_history,
                    parent,
                    false
                )

        return AdviceHistoryViewHolder(view, onItemClick)
    }

    override fun onBindViewHolder(
        holder: AdviceHistoryViewHolder,
        position: Int
    ) {
        holder.bind(items[position])
    }

    override fun getItemCount(): Int =
        items.size

    class AdviceHistoryViewHolder(
        itemView: View,
        private val onItemClick: (AiAdviceResponse) -> Unit
    ) : RecyclerView.ViewHolder(itemView) {

        private val dateText: TextView =
            itemView.findViewById(R.id.tvAdviceHistoryDate)

        private val rangeText: TextView =
            itemView.findViewById(R.id.tvAdviceHistoryRange)

        private val previewText: TextView =
            itemView.findViewById(R.id.tvAdviceHistoryPreview)

        private val modelText: TextView =
            itemView.findViewById(R.id.tvAdviceHistoryModel)

        fun bind(advice: AiAdviceResponse) {
            val adviceDate =
                advice.adviceDate
                    ?: AiTimeFormatter.formatDateTime(advice.createdAt)
                    ?: "Unknown"

            dateText.text =
                "Advice date: $adviceDate"

            val startDate = advice.startDate ?: "--"
            val endDate = advice.endDate ?: "--"
            rangeText.text = "Range: $startDate to $endDate"

            previewText.text =
                preview(
                    advice.adviceText.ifBlank {
                        "No advice text is available."
                    }
                )

            if (advice.modelName.isNullOrBlank()) {
                modelText.visibility = View.GONE
                modelText.text = ""
            } else {
                modelText.visibility = View.VISIBLE
                modelText.text = "Generated by: ${advice.modelName}"
            }

            itemView.setOnClickListener {
                onItemClick(advice)
            }
        }

        private fun preview(value: String): String {
            val collapsed =
                value.replace(Regex("\\s+"), " ").trim()

            return if (collapsed.length > MAX_PREVIEW_LENGTH) {
                collapsed.take(MAX_PREVIEW_LENGTH - 3) + "..."
            } else {
                collapsed
            }
        }
    }

    private companion object {
        const val MAX_PREVIEW_LENGTH = 140
    }
}
