package com.example.wellnessapp.ui.ai

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.recyclerview.widget.RecyclerView
import com.example.wellnessapp.R
import com.example.wellnessapp.data.model.ChatMessageResponse

/**
 * Displays user and assistant message bubbles.
 *
 * @author Yunke Deng
 */
class ChatMessageAdapter :
    RecyclerView.Adapter<RecyclerView.ViewHolder>() {

    private val messages =
        mutableListOf<ChatMessageResponse>()

    fun submitMessages(
        newMessages: List<ChatMessageResponse>
    ) {
        messages.clear()
        messages.addAll(newMessages)
        notifyDataSetChanged()
    }

    override fun getItemCount(): Int =
        messages.size

    override fun getItemViewType(
        position: Int
    ): Int {
        return if (
            messages[position].role.equals(
                "USER",
                ignoreCase = true
            )
        ) {
            VIEW_TYPE_USER
        } else {
            VIEW_TYPE_AI
        }
    }

    override fun onCreateViewHolder(
        parent: ViewGroup,
        viewType: Int
    ): RecyclerView.ViewHolder {
        val inflater =
            LayoutInflater.from(parent.context)

        return if (viewType == VIEW_TYPE_USER) {
            val view = inflater.inflate(
                R.layout.item_chat_user,
                parent,
                false
            )

            UserMessageViewHolder(view)
        } else {
            val view = inflater.inflate(
                R.layout.item_chat_ai,
                parent,
                false
            )

            AiMessageViewHolder(view)
        }
    }

    override fun onBindViewHolder(
        holder: RecyclerView.ViewHolder,
        position: Int
    ) {
        val message = messages[position]

        when (holder) {
            is UserMessageViewHolder ->
                holder.bind(message)

            is AiMessageViewHolder ->
                holder.bind(message)
        }
    }

    private class UserMessageViewHolder(
        itemView: View
    ) : RecyclerView.ViewHolder(itemView) {

        private val messageText: TextView =
            itemView.findViewById(
                R.id.tvUserMessage
            )

        fun bind(message: ChatMessageResponse) {
            messageText.text = message.content
        }
    }

    private class AiMessageViewHolder(
        itemView: View
    ) : RecyclerView.ViewHolder(itemView) {

        private val messageText: TextView =
            itemView.findViewById(
                R.id.tvAiMessage
            )

        private val modelText: TextView =
            itemView.findViewById(
                R.id.tvAiModel
            )

        fun bind(message: ChatMessageResponse) {
            messageText.text = message.content

            if (message.modelName.isNullOrBlank()) {
                modelText.visibility = View.GONE
                modelText.text = ""
            } else {
                modelText.visibility = View.VISIBLE
                modelText.text =
                    "Generated by: ${message.modelName}"
            }
        }
    }

    private companion object {
        const val VIEW_TYPE_USER = 1
        const val VIEW_TYPE_AI = 2
    }
}